import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import IridescentBackground from "@/components/IridescentBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "George Mahashe",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={`
        ${geistSans.variable}
        ${geistMono.variable}
        antialiased

        min-h-dvh
        relative
        isolate
      `}
    >
      <IridescentBackground opacity={0.35} />
      <div className="relative z-10">
        <Header />

        <main>{children}</main>

        <Footer />
      </div>
    </div>
  );
}